"""Report template generator — H1, Bugcrowd, Intigriti, and generic markdown."""

from datetime import datetime
from backend.models.finding import FindingRead


SEVERITY_EMOJI = {
    "Critical": "🔴",
    "High": "🟠",
    "Medium": "🟡",
    "Low": "🔵",
    "Informational": "⚪",
}


def _curl_from_evidence(evidence: str) -> str:
    """
    Attempt to reconstruct a curl command from raw HTTP request/response text.
    Heuristic — works for simple cases.
    """
    lines = evidence.strip().split("\n")
    if not lines:
        return ""

    try:
        request_line = lines[0]  # e.g. "GET /api/users HTTP/1.1"
        parts = request_line.split()
        if len(parts) < 2:
            return ""
        method, path = parts[0], parts[1]

        # Extract headers
        headers = {}
        body_start = 0
        for i, line in enumerate(lines[1:], 1):
            if line.strip() == "":
                body_start = i + 1
                break
            if ":" in line:
                k, v = line.split(":", 1)
                headers[k.strip()] = v.strip()

        host = headers.get("Host", "TARGET_HOST")
        scheme = "https"
        url = f"{scheme}://{host}{path}"

        curl_parts = [f"curl -X {method} '{url}'"]
        for k, v in headers.items():
            if k.lower() not in ("host", "content-length"):
                curl_parts.append(f"  -H '{k}: {v}'")

        if body_start and body_start < len(lines):
            body = "\n".join(lines[body_start:]).strip()
            if body:
                curl_parts.append(f"  -d '{body}'")

        return " \\\n".join(curl_parts)
    except Exception:
        return "# Could not reconstruct curl — paste raw request above"


def _steps_to_numbered(steps: str) -> str:
    """Ensure steps are in numbered markdown list format."""
    lines = [l.strip() for l in steps.strip().split("\n") if l.strip()]
    numbered = []
    counter = 1
    for line in lines:
        # Strip existing numbering
        clean = re.sub(r'^\d+[.)]\s*', '', line)
        numbered.append(f"{counter}. {clean}")
        counter += 1
    return "\n".join(numbered)


import re


def generate_hackerone(f: FindingRead) -> str:
    emoji = SEVERITY_EMOJI.get(f.severity, "⚪")
    curl = _curl_from_evidence(f.evidence) if f.evidence else "# Add curl command or request here"
    steps = _steps_to_numbered(f.steps_to_reproduce) if f.steps_to_reproduce else "1. [Add steps]"

    return f"""## {f.title}

**Vulnerability Type:** {f.vuln_class}
**Severity:** {emoji} {f.severity}
**CVSS Score:** {f.cvss_score} ({f.cvss_vector or 'N/A'})
**Affected Endpoint:** `{f.endpoint}`{f" — Parameter: `{f.parameter}`" if f.parameter else ""}

---

## Summary

{f.impact or '[Describe the impact of this vulnerability]'}

---

## Steps to Reproduce

{steps}

---

## Evidence

```
{f.evidence or '# Paste request/response here'}
```

**Reconstructed curl command:**
```bash
{curl}
```

---

## Impact

{f.impact or '[Describe what an attacker could achieve]'}

---

## Remediation

{f.remediation or '[Add remediation suggestion]'}

---

*Report generated by BugCopilot on {datetime.utcnow().strftime('%Y-%m-%d')}*
"""


def generate_bugcrowd(f: FindingRead) -> str:
    steps = _steps_to_numbered(f.steps_to_reproduce) if f.steps_to_reproduce else "1. [Add steps]"
    curl = _curl_from_evidence(f.evidence) if f.evidence else ""

    return f"""**Title:** {f.title}

**VRT Category:** {f.vuln_class}
**Target:** {f.endpoint}
**Parameter:** {f.parameter or 'N/A'}
**HTTP Method:** {f.http_method}

---

### Description

{f.impact or '[Describe the vulnerability]'}

### Steps to Reproduce

{steps}

### Proof of Concept

```http
{f.evidence or '# Paste HTTP request/response here'}
```

```bash
{curl}
```

### Impact

{f.impact or '[Describe the business/security impact]'}

### Suggested Fix

{f.remediation or '[Suggest a remediation approach]'}

**CVSS:** {f.cvss_score} — {f.cvss_vector or 'N/A'}
*Generated: {datetime.utcnow().strftime('%Y-%m-%d')}*
"""


def generate_intigriti(f: FindingRead) -> str:
    steps = _steps_to_numbered(f.steps_to_reproduce) if f.steps_to_reproduce else "1. [Add steps]"

    return f"""# {f.title}

## Basic Information

| Field | Value |
|---|---|
| Vulnerability Type | {f.vuln_class} |
| Severity | {f.severity} |
| CVSS Score | {f.cvss_score} |
| CVSS Vector | `{f.cvss_vector or 'N/A'}` |
| Affected URL | `{f.endpoint}` |
| Affected Parameter | `{f.parameter or 'N/A'}` |
| HTTP Method | {f.http_method} |

## Description

{f.impact or '[Describe the vulnerability and its context]'}

## Steps to Reproduce

{steps}

## Proof of Concept

```http
{f.evidence or '# Paste HTTP request/response here'}
```

## Impact

{f.impact or '[Describe what an attacker could achieve with this vulnerability]'}

## Recommended Fix

{f.remediation or '[Describe how the vulnerability should be fixed]'}

---
*Report prepared with BugCopilot — {datetime.utcnow().strftime('%Y-%m-%d')}*
"""


def generate_generic(f: FindingRead) -> str:
    steps = _steps_to_numbered(f.steps_to_reproduce) if f.steps_to_reproduce else "1. [Add steps]"
    curl = _curl_from_evidence(f.evidence) if f.evidence else ""

    return f"""# Security Finding: {f.title}

**Date:** {datetime.utcnow().strftime('%Y-%m-%d')}
**Status:** {f.status.capitalize()}

## Classification

- **Vulnerability Class:** {f.vuln_class}
- **Severity:** {f.severity}
- **CVSS 3.1 Score:** {f.cvss_score}
- **CVSS Vector:** {f.cvss_vector or 'N/A'}
- **Estimated Bounty:** ${f.bounty_low}–${f.bounty_high}

## Target

- **Endpoint:** `{f.endpoint}`
- **Parameter:** `{f.parameter or 'N/A'}`
- **HTTP Method:** `{f.http_method}`

## Description

{f.impact or '[Describe the vulnerability]'}

## Steps to Reproduce

{steps}

## Evidence

```http
{f.evidence or '# Paste HTTP request/response'}
```

{f"```bash\n{curl}\n```" if curl else ""}

## Impact

{f.impact or '[Describe impact]'}

## Remediation

{f.remediation or '[Describe fix]'}

## Notes

{f.notes or 'N/A'}
"""


PLATFORM_GENERATORS = {
    "hackerone": generate_hackerone,
    "bugcrowd": generate_bugcrowd,
    "intigriti": generate_intigriti,
    "generic": generate_generic,
}


def generate_report(f: FindingRead, platform: str = "generic") -> str:
    generator = PLATFORM_GENERATORS.get(platform.lower(), generate_generic)
    return generator(f)
